spring.application.name=aqua-control-api
spring.datasource.url=${SECRET_CONFIG_DB_URL}
spring.datasource.password=${SECRET_CONFIG_DB_PASSWORD}
spring.datasource.username=${SECRET_CONFIG_DB_USERNAME}
spring.jpa.hibernate.ddl-auto=update
server.port=${CONFIG_HTTP_HTTPS_PORT}
logging.level.org.hibernate=WARN
logging.pattern.console=%d{dd MMM yyyy HH:mm:ss.SSS}%c[%M]: %p %m%n


